apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: goserver
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  # Server para definir a % q o CPU deve estar para ele criar uma nova replica
  targetCPUUtilizationPercentage: 30